# Generated by Django 3.2.4 on 2021-06-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='caustic_sova',
        ),
        migrations.AddField(
            model_name='testresult',
            name='caustic_soda',
            field=models.CharField(default='(Non-Adulterated)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='acidity',
            field=models.CharField(default='(Non-Adulterated)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='antibiotic',
            field=models.CharField(default='(Non-Adulterated)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='detergent',
            field=models.CharField(default='(Non-Adulterated)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='fat',
            field=models.CharField(default='(Non-Adulterated)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='snf',
            field=models.CharField(default='(Non-Adulterated)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='starch',
            field=models.CharField(default='(Non-Adulterated)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='urea',
            field=models.CharField(default='(Non-Adulterated)', max_length=1000),
        ),
    ]
