# Generated by Django 3.2.4 on 2021-06-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210629_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='fat',
            field=models.CharField(blank=True, default='(Non-Adulterated)', max_length=1000, null=True),
        ),
    ]
