# Generated by Django 3.2.4 on 2021-06-29 08:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_testresult_fat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='testresult',
            name='fat',
            field=models.CharField(default='(Non-Adulterated)', max_length=1000),
        ),
    ]
