# Generated by Django 3.2.4 on 2021-06-29 14:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210629_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
