# Generated by Django 3.2.4 on 2021-06-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_testresult_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test_date',
            field=models.DateField(),
        ),
    ]
