# Generated by Django 3.2.4 on 2021-06-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_testresult_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
